import numpy as np
from ..cad.model_manager import ModelManager

class StructuralAnalysis:
    def __init__(self, model_id):
        self.model_manager = ModelManager.get_instance()
        self.model = self.model_manager.get_model(model_id)

    def prepare_inp_file(self, material_properties, loads, constraints):
        # Convert our model to CalculiX input format
        # This is a simplified version and would need to be expanded
        inp_content = "*NODE\n"
        for i, vertex in enumerate(self.model.vertices().vals(), 1):
            inp_content += f"{i}, {vertex.X}, {vertex.Y}, {vertex.Z}\n"

        inp_content += "*ELEMENT, TYPE=C3D8R\n"
        # Add element definitions here

        inp_content += "*MATERIAL, NAME=MATERIAL1\n"
        inp_content += f"*ELASTIC\n{material_properties['young_modulus']}, {material_properties['poisson_ratio']}\n"

        inp_content += "*BOUNDARY\n"
        for constraint in constraints:
            inp_content += f"{constraint['node']}, {constraint['dof']}, {constraint['value']}\n"

        inp_content += "*STEP\n*STATIC\n"
        inp_content += "*CLOAD\n"
        for load in loads:
            inp_content += f"{load['node']}, {load['direction']}, {load['magnitude']}\n"

        inp_content += "*NODE PRINT, NSET=NALL\nU\n*EL PRINT, ELSET=EALL\nS\n*END STEP"

        with open('model.inp', 'w') as f:
            f.write(inp_content)

    def run_analysis(self):
        # Run CalculiX
        subprocess.run(["ccx", "model"])

    def process_results(self):
        # Process the .frd file generated by CalculiX
        # This is a simplified version and would need to be expanded
        results = {}
        with open('model.frd', 'r') as f:
            lines = f.readlines()
            for i, line in enumerate(lines):
                if line.strip().startswith('1PSTRESS'):
                    # Extract stress values
                    stress_values = [float(val) for val in lines[i+1].split()]
                    results[f'node_{i}'] = {
                        'stress': max(stress_values)
                    }
        return results

    def perform_analysis(self, material_properties, loads, constraints):
        self.prepare_inp_file(material_properties, loads, constraints)
        self.run_analysis()
        return self.process_results()

    def generate_recommendations(self, failure_point, material_properties):
        recommendations = []
        
        # Recommendation based on safety factor
        if failure_point['safety_factor'] < 1:
            recommendations.append("Critical: Immediate redesign required. The part is likely to fail under the given load.")
        elif failure_point['safety_factor'] < 1.5:
            recommendations.append("Increase the thickness or change the geometry of this area to improve the safety factor.")
        
        # Recommendation based on stress concentration
        if failure_point['stress'] > 0.8 * material_properties['yield_strength']:
            recommendations.append("Consider adding fillets or chamfers to reduce stress concentration in this area.")
        
        # Recommendation based on material
        if failure_point['stress'] > 0.5 * material_properties['yield_strength']:
            recommendations.append("Consider using a stronger material with a higher yield strength in this area.")
        
        # Recommendation for load redistribution
        recommendations.append("Analyze the load path and consider redistributing the load to reduce stress in this area.")
        
        return recommendations

    def identify_failure_points(self, results, material_properties):
        failure_points = []
        for node, data in results.items():
            safety_factor = material_properties['yield_strength'] / data['stress']
            if safety_factor < 2:  # Consider points with safety factor < 2 as potential failure points
                severity = 1 - (safety_factor / 2)  # Normalize severity between 0 and 1
                failure_point = {
                    'node': node,
                    'position': data['position'],
                    'stress': data['stress'],
                    'safety_factor': safety_factor,
                    'severity': severity
                }
                failure_point['recommendations'] = self.generate_recommendations(failure_point, material_properties)
                failure_points.append(failure_point)

        # Sort failure points by severity (highest to lowest)
        failure_points.sort(key=lambda x: x['severity'], reverse=True)
        return failure_points[:5]  # Return top 5 most severe points

    def perform_analysis(self, material_properties, loads, constraints):
        self.prepare_inp_file(material_properties, loads, constraints)
        self.run_analysis()
        results = self.process_results()
        failure_points = self.identify_failure_points(results, material_properties)
        return results, failure_points